---
version: '3'
### Source: https://github.com/Archef2000/pivpn-docker/
services:
  plebvpn-client:
    # Image is built from plebvpn-client-docker
    image: plebvpn-client
    container_name: plebvpn-client
    # host networking doesn't quite work correctly, but is convenient for development
    network_mode: host
#    ports:
#      - 42000:42099/udp
    volumes:
      - ./:/plebvpn-client
    privileged: true # Is needed to run Openvpn

volumes:
  plebvpn_data:
